# Generated by Django 3.1.1 on 2020-09-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.ImageField(upload_to='pics')),
                ('surname', models.CharField(default='surname', max_length=20)),
                ('first_name', models.CharField(default='first name', max_length=20)),
                ('other_names', models.CharField(default='other names', max_length=20)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=30)),
                ('phone_number', models.IntegerField()),
                ('phone_number_2', models.IntegerField()),
                ('marital_status', models.CharField(choices=[('SG', 'single'), ('MD', 'married'), ('DV', 'divorced'), ('FR', 'freed')], max_length=20)),
                ('date_of_birth', models.DateTimeField()),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender_2', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=20)),
                ('relationship', models.CharField(choices=[('B', 'brother'), ('S', 'sister'), ('F', 'father'), ('M', 'mother')], max_length=20)),
            ],
        ),
    ]
