# Generated by Django 3.1rc1 on 2020-08-06 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200730_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.vacancy')),
            ],
        ),
    ]
